import { env } from "cloudflare:workers";

type SeedSignal = [string,string,string,string,string,string,string,string,string,string,string];
const seedSignals: SeedSignal[] = [
  ["S008","Protected Areas","The restoration-plan deadline creates an immediate tourism input window","EU Member States are expected to submit draft National Restoration Plans by 1 September 2026.","Protected-area access, restoration works and visitor-management assumptions may be affected before plans harden.","HIGH","Two direct EU sources establish the requirement and deadline.","P1","ADOPT","Review the relevant draft and log every tourism-access or monitoring implication before 1 September.","Review when each material implication is linked to a project decision."],
  ["S002","AI","EU transparency duties now apply to tourism-facing AI interactions","Article 50 transparency obligations began applying on 2 August 2026.","Tourism chatbots and public-information content need explicit disclosure and human-confirmation boundaries.","HIGH","Two direct Commission sources establish the applicable date and duties.","P1","TEST","Audit one chatbot flow and one public-information flow before release.","Review when both flows have documented scope and labeling decisions."],
  ["S012","Tourism Data","Platform-booked short stays grew far faster than total accommodation nights","Platform-booked nights grew 11.4% in 2025 while total accommodation nights grew 2.2%; scopes differ.","Aggregate totals may understate the speed and concentration of platform-mediated pressure.","HIGH","Two Eurostat series establish the respective rates; local comparability remains untested.","P1","TEST","Reconcile local platform and accommodation series before changing pressure indicators.","Review when geography, definitions and coverage are aligned."],
  ["S001","Remote Sensing","AlphaEarth embeddings are accessible, but tourism-monitoring value is unvalidated","Annual satellite embeddings for 2017–2025 are accessible through Earth Engine and cloud storage.","The access barrier has fallen, but premature integration could add opaque complexity.","HIGH","Provider documentation confirms availability, not fitness for the tourism use.","P1","TEST","Compare AlphaEarth with the current baseline on two known sites.","Review when accuracy, interpretability and processing cost are recorded."],
  ["S003","Governance","EU short-term-rental rules create a monthly evidence channel","EU rules now standardize identifiers, platform checks and monthly delivery through national entry points.","Destination teams may gain systematic supply data, subject to local implementation.","HIGH","Legal and implementation sources establish the framework.","P1","TEST","Map the local registration scheme and usable fields before redesigning indicators.","Review when one jurisdiction's access path and cadence are verified."],
  ["S004","Tourism Technology","Booking DMA rules create formal leverage, but realized benefit remains contested","Business users gained direct-channel and data rights while practical outcomes remain disputed.","A legal entitlement does not automatically change price dispersion or platform dependence.","MEDIUM","Direct legal evidence is strong; outcome evidence is mixed.","P1","TEST","Compare direct and platform prices plus exports for 20 local properties.","Review when price gaps and access barriers are recorded."],
  ["S005","Mobility","The EU Entry/Exit System is operational at external borders","The Entry/Exit System completed progressive implementation on 10 April 2026.","Border-process changes may alter arrival friction, but destination-level effects are unknown.","HIGH","Official operational guidance establishes implementation.","P2","MONITOR","Track comparable wait-time evidence at two relevant gateways.","Review when a responsible authority publishes comparable performance data."],
  ["S006","Aviation","The 2% SAF mandate is active while supply remains concentrated","ReFuelEU sets a 2% sustainable aviation fuel floor; supply remains concentrated.","Route-level price or emissions effects cannot be inferred from the policy floor alone.","MEDIUM","Policy is direct; operational transfer to a destination remains uncertain.","P3","MONITOR","","Review when route-level cost or emissions data become available."],
  ["S007","Accessibility","Accessibility requirements cover tourism e-commerce and transport interfaces","The European Accessibility Act applies to covered e-commerce and transport-information services.","Booking and information journeys need end-to-end accessibility, not a generic compliance claim.","HIGH","A direct Commission source establishes the application and service categories.","P1","TEST","Audit one complete booking journey against applicable requirements.","Review when blockers, owners and remediation decisions are recorded."],
  ["S009","Climate","Heat stress is intensifying while aggregate tourism nights grow","European climate evidence shows rising heat stress while aggregate accommodation nights reached a record.","Capacity decisions need local heat-response evidence rather than an assumed Europe-wide demand effect.","HIGH","Authoritative datasets establish both trends; causality remains unresolved.","P1","TEST","Compare UTCI and visitor counts across two documented heatwaves.","Review when effect direction, lag and limitations are documented."],
  ["S010","Wildfire","Record wildfire exposure raises a capacity question, not an automatic threshold","The EU recorded its largest burnt area in 2025; 2026 conditions do not support simple escalation.","Visitor limits should reflect actual restrictions rather than burnt-area headlines alone.","HIGH","Direct JRC reporting supports the record and comparison.","P1","TEST","Overlay closures and fire-danger levels with visitor thresholds at two sites.","Review when the binding restriction is identified."],
  ["S011","Water","The EU water-efficiency target creates an operational benchmark","The EU targets at least 10% greater water efficiency by 2030 amid seasonal scarcity.","Destinations need measured baselines before translating the target into constraints.","MEDIUM","Policy direction is clear; local transferability is uncertain.","P2","TEST","Run a one-site water audit before adding a capacity constraint.","Review when baseline use and feasible interventions are documented."],
  ["S013","Mobility Data","The Data Act opens vehicle data access, not automatic destination access","Users gained connected-product data rights, dependent on role and lawful sharing paths.","Governance and availability must be proven before architecture changes.","MEDIUM","Direct guidance supports rights and explicitly limits transferability.","P2","TEST","Ask one data holder for fields, rights and a lawful sharing path.","Review when a schema and access decision are documented."],
  ["S014","Tourism Data","MNO mobility data is promising but needs bias validation","Official bodies document tourism use cases alongside privacy, access and methodological barriers.","Visitor-pressure decisions could become precise-looking but systematically biased.","MEDIUM","Use cases support feasibility; representativeness remains contested.","P1","TEST","Benchmark one MNO series against ground truth in resident- and visitor-heavy zones.","Review when bias by zone and time is quantified."],
  ["S015","Data Governance","Tourism data-space rollout remains a watch, not a dependency","EU initiatives continue, but reviewed material does not establish production-ready assets.","Designing around hypothetical availability risks premature architecture.","MEDIUM","Policy intent is established; operational readiness is not.","P3","MONITOR","","Review when an accessible catalogue and governance terms exist."],
];
const sourceSeeds = [
  ["Nature Restoration Regulation","European Commission","POLICY_OR_REGULATION","https://environment.ec.europa.eu/topics/nature-and-biodiversity/nature-restoration-regulation_en","2024-08-18"],
  ["AI Act transparency obligations","European Commission","POLICY_OR_REGULATION","https://digital-strategy.ec.europa.eu/en/library/guidelines-transparency-obligations-providers-and-deployers-ai-systems","2026-07-20"],
  ["Platform tourism nights in 2025","Eurostat","DATASET_OR_DOCUMENTATION","https://ec.europa.eu/eurostat/web/products-eurostat-news/w/ddn-20260401-1","2026-04-01"],
  ["AlphaEarth Foundations","Google DeepMind","OFFICIAL_ANNOUNCEMENT","https://deepmind.google/blog/alphaearth-foundations-helps-map-our-planet-in-unprecedented-detail/","2025-07-30"],
  ["Short-term rental transparency rules","European Commission","POLICY_OR_REGULATION","https://single-market-economy.ec.europa.eu/news/new-rules-bring-increased-transparency-short-term-rentals-sector-2026-05-20_en","2026-05-20"],
  ["2025 EU wildfire season","European Commission JRC","TECHNICAL_REPORT","https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/2025-was-eus-most-destructive-wildfire-season-record-2026-03-31_en","2026-03-31"],
];
const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS signals (id TEXT PRIMARY KEY, domain TEXT NOT NULL, title TEXT NOT NULL, claim TEXT NOT NULL, why_it_matters TEXT NOT NULL, evidence_quality TEXT NOT NULL, evidence_rationale TEXT NOT NULL, priority TEXT NOT NULL, disposition TEXT NOT NULL DEFAULT 'UNDECIDED', workflow_status TEXT NOT NULL DEFAULT 'OPEN', move_text TEXT NOT NULL DEFAULT '', move_state TEXT NOT NULL DEFAULT 'NOT_STARTED', confirmation_state TEXT NOT NULL DEFAULT 'DRAFT', review_trigger TEXT NOT NULL DEFAULT '', as_of_date TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS sources (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, publisher TEXT NOT NULL, source_type TEXT NOT NULL, locator TEXT NOT NULL, publication_date TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS signal_evidence (id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id TEXT NOT NULL, source_id INTEGER NOT NULL, relationship TEXT NOT NULL, scope_match TEXT NOT NULL, evidence_note TEXT NOT NULL DEFAULT '')`,
  `CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE')`,
  `CREATE TABLE IF NOT EXISTS signal_projects (id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id TEXT NOT NULL, project_id TEXT NOT NULL, reason TEXT NOT NULL, confirmed_by_user INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS signal_events (id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id TEXT NOT NULL, event_type TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS idx_signals_priority_status ON signals(priority, workflow_status)`, `CREATE INDEX IF NOT EXISTS idx_signal_evidence_signal ON signal_evidence(signal_id)`, `CREATE INDEX IF NOT EXISTS idx_signal_projects_signal ON signal_projects(signal_id)`, `CREATE INDEX IF NOT EXISTS idx_signal_events_signal ON signal_events(signal_id, created_at)`,
];
export function getD1(){ if(!env.DB) throw new Error("D1 binding DB is unavailable"); return env.DB; }
export async function ensureDatabase(){
  const db=getD1(); await db.batch(schemaStatements.map((s)=>db.prepare(s))); const count=await db.prepare("SELECT COUNT(*) AS count FROM signals").first<{count:number}>();
  if((count?.count??0)===0){
    await db.batch(seedSignals.map((s)=>db.prepare(`INSERT INTO signals (id,domain,title,claim,why_it_matters,evidence_quality,evidence_rationale,priority,disposition,move_text,review_trigger,as_of_date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(...s,"2026-08-21")));
    await db.batch(sourceSeeds.map((s)=>db.prepare(`INSERT INTO sources (title,publisher,source_type,locator,publication_date) VALUES (?,?,?,?,?)`).bind(...s)));
    await db.batch([["P001","Visitor Capacity","Operational visitor and vehicle capacity decisions."],["P002","Destination Observatory","Cross-domain monitoring and indicators."],["P003","Climate Adaptation","Destination climate and ecological adaptation."],["P004","Tourism Assistant","Tourism-facing digital services and business support."]].map((x)=>db.prepare("INSERT INTO projects VALUES (?,?,?,'ACTIVE')").bind(...x)));
    await db.batch([["S008","P001","Restoration measures may affect protected-area access."],["S002","P004","AI transparency affects public-facing product flows."],["S012","P002","Platform growth may change pressure indicators."],["S009","P003","Heat exposure affects adaptation decisions."],["S010","P001","Fire restrictions may become a binding constraint."],["S014","P002","MNO data could improve or distort monitoring."]].map((x)=>db.prepare("INSERT INTO signal_projects (signal_id,project_id,reason) VALUES (?,?,?)").bind(...x)));
    await db.batch([["S008",1,"SUPPORTS"],["S002",2,"SUPPORTS"],["S012",3,"SUPPORTS"],["S001",4,"SUPPORTS"],["S003",5,"SUPPORTS"],["S010",6,"SUPPORTS"]].map((x)=>db.prepare("INSERT INTO signal_evidence (signal_id,source_id,relationship,scope_match) VALUES (?,?,?,'DIRECT')").bind(...x)));
  } return db;
}
